name: devops-practice
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - name: Checkout reppository code
        uses: actions/checkout@v3
      - uses: joschi/setup-jdk@v3
        with:
          java-version: 17
      - name: Build
        run: ./gradlew build
